# name: Build and Deploy
# on:
#   push:
#     branches:
#       - master
# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: All things angular
#       uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2 ## replace by latest version without it you will see Expected format {org}/{repo}[/path]@ref. Actual 'AhsanAyaz/angular-deploy-gh-pages-actions',Input string was not in a correct format.
#       with:
#         github_access_token: ${{ secrets.ACCESS_TOKEN }} # see the Configuration section for how you can create secrets
#         build_configuration: production  # The build environment for the app. please look configurations in your angular.json
#         base_href: /   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
#         deploy_branch: master # The branch the action should deploy to.
#         angular_dist_build_folder: dist/Resume # The folder where your project is supposed to be after running ng build by the action.
name: GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: dist/Resume
        enable_jekyll: true
